### ISSUE TITLE
Title Menu Creation

### ISSUE THREAD

**Issue by lilimuth** [westl/CS113#22]
Preliminary work for the Title Screen

**Comment by mpowell2** [comment]
![pippin to the rescue 2](https://cloud.githubusercontent.com/assets/14946458/11262600/02418b76-8e36-11e5-979e-77eafd370df1.jpg)
![basic menu sketch](https://cloud.githubusercontent.com/assets/14946458/11261982/6eb3e928-8e2e-11e5-8a57-64350ed288c8.JPG)
![subtraction button](https://cloud.githubusercontent.com/assets/14946458/11261976/6e987e7c-8e2e-11e5-91e0-9b0cb6f41395.png)
![addition button](https://cloud.githubusercontent.com/assets/14946458/11261978/6eaaf700-8e2e-11e5-8d35-93fde7874d89.png)
![colors button](https://cloud.githubusercontent.com/assets/14946458/11261981/6eb27804-8e2e-11e5-9474-10295706a705.png)
![countin button](https://cloud.githubusercontent.com/assets/14946458/11261979/6eb1639c-8e2e-11e5-8812-1ec862782ba5.png)
![measurement button](https://cloud.githubusercontent.com/assets/14946458/11261980/6eb2487a-8e2e-11e5-8758-1d27a7068751.png)
