### ISSUE TITLE
Scientist friend Sprite finish and import

### ISSUE THREAD

**Issue by lilimuth** [westl/CS113#44]
Finish the scientist friend Sprite and import it into the game.

**Comment by akkeech** [comment]
Finishing the sprite and importing should be separate issues.

**Comment by lilimuth** [comment]
It doesn't necessarily need to be. Import simply means to put it into the assets folder so we can all access it. It doesn't require any additional work.

**Comment by lilimuth** [comment]
Reopening until pushed into Master (apparently)
