### ISSUE TITLE
Fix the quiz window and add assets

### ISSUE THREAD

**Issue by lilimuth** [westl/CS113#48]
The quiz window cannot be closed once it is open. Even if the question is correctly answered. There is also no sound playing when the answers are made, the audio appears to be missing.

The text needs to be made bigger so it is easier for children to read. And finally, the assets need to be built into the window. Right now they either do not show up, or are stretched and fall outside the quiz window.

**Comment by kaseanherrera** [comment]
Going to reopen because it is not rigged on master
