### ISSUE TITLE
Give better names to game objects.

### ISSUE THREAD

**Issue by kaseanherrera** [westl/CS113#51]
We can not name everything floor. 
Change Stair Objects to : "Stair"
Change random Boxes to : "Box"

**Comment by lilimuth** [comment]
Finished.

**Comment by kaseanherrera** [comment]
GOing to reOpen because all of the stair tiles are not named on the master

**Comment by lilimuth** [comment]
This already is on master.

**Comment by lilimuth** [comment]
Closing out. Verified in Master Branch.
